server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://dpg-d7l65977f7vs73as19c0-a.oregon-postgres.render.com/eficiencia_energetica
spring.datasource.username=amanda
spring.datasource.password=eVM056MRHkqC0A01yzSAptIXBKQWXczV
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect